// Typed catalog of every JSONL event the catalyst-code core can emit.
// Kept in sync with `core/src/**` `Event::new("...")` call sites.
//
// `CoreEvent` is intentionally an open `{ type: string } & Record<string, unknown>`
// at the wire boundary (unknown future events must not break the SDK). The
// `CORE_EVENT_TYPES` list + per-kind interfaces below are the documented,
// autocomplete-friendly surface for known events.

/** Every known core event `type` string (alphabetical). */
export const CORE_EVENT_TYPES = [
  "aborted",
  "agents",
  "approval_changed",
  "approval_expired",
  "approval_request",
  "ask_request",
  "audit",
  "authed",
  "bash_execution",
  "checkpoint_created",
  "checkpoint_restored",
  "checkpoints",
  "compacted",
  "compacting",
  "config_changed",
  "context_breakdown",
  "cost_update",
  "delta",
  "digested",
  "done",
  "error",
  "file_change",
  "goal_certified",
  "goal_completion_summary",
  "goal_iteration",
  "goal_phase",
  "goal_plan",
  "goal_review_verdict",
  "goal_state",
  "goal_step_complete",
  "goal_step_verdict",
  "goal_verify_verdict",
  "history",
  "http_retry",
  "info",
  "intercom_message",
  "memory_list",
  "memory_saved",
  "metrics",
  "models",
  "models_refreshed",
  "oauth_prompt",
  "plugin_commands",
  "plugin_disabled",
  "plugin_enabled",
  "plugin_error",
  "plugin_installed",
  "plugin_removed",
  "plugin_status",
  "plugins_list",
  "plugin_trust_applied",
  "plugin_trust_prompt",
  "protocol_hello",
  "provider_changed",
  "provider_presets",
  "ready",
  "reflecting",
  "reset",
  "run_cancelled",
  "runtime_status",
  "search_key_set",
  "session_change_failed",
  "session_changed",
  "session_deleted",
  "session_pinned",
  "session_recovered",
  "session_renamed",
  "sessions",
  "skills",
  "stats",
  "steer",
  "subagent_done",
  "subagent_message",
  "subagent_progress",
  "subagent_start",
  "subagent_tool_call",
  "subagent_tool_result",
  "sudo_request",
  "thinking",
  "tool_call",
  "tool_call_args",
  "tool_call_name",
  "tool_call_start",
  "tool_result",
  "umans_conc",
  "usage",
  "vision_config",
  "work_state",
  "worktree_cleaned",
  "worktree_promoted",
  "worktree_ready",
  "worktree_seeded",
  // New events are appended in core-insertion order (the checked-in
  // events-v2.jsonl fixture is generated by the core, not sorted). Keep the
  // catalog byte-identical to the fixture so the catalog test stays green.
  "provider_models_preview",
  "sandbox_status",
  "sandbox_prepare_progress",
  "sandbox_ready",
  "sandbox_error",
  "stuck_nudge",
  "summary_required",
  "advisor_note",
  "advisor_status",
  "skill_marketplace_state",
  "skill_marketplace_results",
  "skill_marketplace_changed",
  "skill_marketplace_error",
] as const;

export type CoreEventType = (typeof CORE_EVENT_TYPES)[number];

export function isKnownCoreEventType(type: string): type is CoreEventType {
  return (CORE_EVENT_TYPES as readonly string[]).includes(type);
}

/** Wire-level core event. Always has `type`; other fields vary by kind. */
export interface ProtocolMetadata {
  protocol_version?: number;
  session_id?: string;
  run_id?: string;
  sequence?: number;
}

export type CoreEvent = { type: string } & ProtocolMetadata & Record<string, unknown>;

export interface RuntimeResource {
  id: number;
  kind: string;
  label: string;
  session_id: string;
  run_id?: string;
  cancelled: boolean;
}

export interface RuntimeStatusEvent extends ProtocolMetadata {
  type: "runtime_status";
  discarded_stale_results: number;
  resources: RuntimeResource[];
  pending_approvals: number;
  pending_asks: number;
  pending_sudos: number;
}

export type ToolResultStatus =
  | "success"
  | "denied"
  | "cancelled"
  | "timed_out"
  | "failed"
  | "stale"
  | "partially_completed";

export interface ToolResultEvent extends ProtocolMetadata {
  type: "tool_result";
  id: string;
  ok: boolean;
  status: ToolResultStatus;
  output: string;
  diff?: string;
  tool?: string;
}

export interface SessionRecoveredEvent extends ProtocolMetadata {
  type: "session_recovered";
  warnings: string[];
  interrupted_runs: string[];
}

// ── Narrow helpers for common / newly added events ──

export interface ProtocolHelloEvent {
  type: "protocol_hello";
  version: string;
  protocol_version: number;
  min_client: string;
  capabilities: string[];
}

export interface FileChangeEvent {
  type: "file_change";
  path: string;
  unified_diff?: string;
  tool: string;
  agent_id?: string;
  run_id?: string;
}

export interface PluginTrustEntry {
  name: string;
  version?: string;
  description?: string;
  path?: string;
  /** "" = undecided | "trust" | "deny". */
  decision: "" | "trust" | "deny";
}

export interface PluginTrustPromptEvent extends ProtocolMetadata {
  type: "plugin_trust_prompt";
  plugins: PluginTrustEntry[];
}

export interface PluginTrustAppliedEvent extends ProtocolMetadata {
  type: "plugin_trust_applied";
  trusted: string[];
  denied: string[];
  loaded: number;
}

export interface CheckpointCreatedEvent {
  type: "checkpoint_created";
  id: string;
  label: string;
  kind: string;
  auto?: boolean;
  paths?: string[];
}

export interface CheckpointRestoredEvent {
  type: "checkpoint_restored";
  id: string;
  kind: string;
}

export interface CheckpointsEvent {
  type: "checkpoints";
  checkpoints: Array<Record<string, unknown>>;
}

export interface WorktreeReadyEvent {
  type: "worktree_ready";
  run_id: string;
  path: string;
  branch?: string;
}

export interface WorktreeCleanedEvent {
  type: "worktree_cleaned";
  path: string;
}

export interface WorktreePromotedEvent {
  type: "worktree_promoted";
  run_id: string;
  paths: string[];
}

export interface AuditEvent {
  type: "audit";
  tool: string;
  decision: string;
  actor: string;
}

export interface CostUpdateEvent {
  type: "cost_update";
  tokens_in?: number;
  tokens_out?: number;
  cached_tokens?: number;
  cache_hit_pct?: number | null;
  estimated_usd?: number | null;
  model?: string;
}

export interface GoalStepVerdictEvent {
  type: "goal_step_verdict";
  ok: boolean;
  output: string;
}

/** One-shot lasting signal when a deploy step settles (alongside goal_state). */
export interface GoalStepCompleteEvent {
  type: "goal_step_complete";
  step_id: string;
  title: string;
  agent: string;
  ok: boolean;
  status: string;
  summary: string;
  run_id?: string;
}

/** Deterministic or wrap-up synthesis text when a goal finishes (esp. skipped wrap-up). */
export interface GoalCompletionSummaryEvent {
  type: "goal_completion_summary";
  /** Primary payload from core (`emit_goal_completion_summary`). */
  text: string;
  /** Defensive alias — UIs may accept `summary` if `text` is absent. */
  summary?: string;
}

export interface GoalStateEvent {
  type: "goal_state";
  [key: string]: unknown;
}

export interface GoalPlanEvent {
  type: "goal_plan";
  summary?: string;
  steps?: unknown[];
  risks?: string[];
  validation?: string[];
  version?: number;
}

export interface GoalPhaseEvent {
  type: "goal_phase";
  from: string;
  to: string;
  message?: string;
  wave?: number;
  step_count?: number;
  done_count?: number;
}

export interface GoalIterationEvent {
  type: "goal_iteration";
  id?: string;
  iteration: number;
  max_iterations: number;
  plan_revision?: number;
  max_plan_revisions?: number;
}

export interface GoalReviewVerdictEvent {
  type: "goal_review_verdict";
  id?: string;
  ok: boolean;
  summary: string;
  iteration?: number;
  plan_revision?: number;
  evidence_paths?: string[];
}

export interface GoalVerifyVerdictEvent {
  type: "goal_verify_verdict";
  id?: string;
  ok: boolean;
  summary: string;
  iteration?: number;
  remaining_gaps?: string[];
  evidence_paths?: string[];
}

export interface GoalCertifiedEvent {
  type: "goal_certified";
  id?: string;
  summary: string;
  iteration?: number;
  certified?: boolean;
}

export interface SubagentStartEvent {
  type: "subagent_start";
  run_id: string;
  mode?: string;
  agent?: string;
  agents?: string[];
  task?: string;
  depth?: number;
  started_at?: number;
}

export interface SubagentDoneEvent {
  type: "subagent_done";
  run_id: string;
  state: string;
  summary?: string;
  ended_at?: number;
}

export interface SubagentProgressEvent {
  type: "subagent_progress";
  run_id: string;
  agent?: string;
  phase?: string;
  detail?: string;
  [key: string]: unknown;
}

export interface ApprovalRequestEvent {
  type: "approval_request";
  request_id: string;
  tool: string;
  args: string;
  diff?: string;
}

export interface AskRequestEvent {
  type: "ask_request";
  request_id: string;
  questions: unknown[];
}

export interface SudoRequestEvent {
  type: "sudo_request";
  request_id: string;
  command: string;
}

export interface MetricsEvent {
  type: "metrics";
  ttft_ms?: number;
  elapsed_ms?: number;
  tokens_in?: number;
  prompt_tokens?: number;
  tokens_out?: number;
  cached_tokens?: number;
  tps?: number;
  tps_est?: number;
  model?: string;
  memory_recall?: unknown;
}

// ── Sandbox lifecycle events (Microsandbox migration) ──
// See sdk/src/sandbox.ts for the typed report/status shapes.

/** `get_sandbox_status` / `reset_sandbox` response. */
export interface SandboxStatusEvent extends ProtocolMetadata {
  type: "sandbox_status";
  /** Effective sandbox mode. */
  mode: string;
  /** Serialized preflight report (snake_case). */
  report?: Record<string, unknown>;
  /** True when this status follows a `reset_sandbox` command. */
  reset?: boolean;
}

/** Streamed while `prepare_sandbox` downloads runtime/image assets. */
export interface SandboxPrepareProgressEvent extends ProtocolMetadata {
  type: "sandbox_prepare_progress";
  /** Current preparation phase, e.g. "downloading-runtime-and-image". */
  phase: string;
}

/** Terminal success of `prepare_sandbox`. */
export interface SandboxReadyEvent extends ProtocolMetadata {
  type: "sandbox_ready";
  /** Whether the sandbox is now ready to execute commands. */
  ready: boolean;
  /** Serialized preflight report (snake_case). */
  report?: Record<string, unknown>;
}

/** Terminal failure of `prepare_sandbox`. */
export interface SandboxErrorEvent extends ProtocolMetadata {
  type: "sandbox_error";
  /** Human-readable error message (never carries secret values). */
  error: string;
}

export type NarrowCoreEvent =
  | ProtocolHelloEvent
  | FileChangeEvent
  | CheckpointCreatedEvent
  | CheckpointRestoredEvent
  | CheckpointsEvent
  | WorktreeReadyEvent
  | WorktreeCleanedEvent
  | WorktreePromotedEvent
  | AuditEvent
  | CostUpdateEvent
  | GoalStepVerdictEvent
  | GoalStepCompleteEvent
  | GoalCompletionSummaryEvent
  | GoalStateEvent
  | GoalPlanEvent
  | GoalPhaseEvent
  | GoalIterationEvent
  | GoalReviewVerdictEvent
  | GoalVerifyVerdictEvent
  | GoalCertifiedEvent
  | SubagentStartEvent
  | SubagentDoneEvent
  | SubagentProgressEvent
  | ApprovalRequestEvent
  | AskRequestEvent
  | SudoRequestEvent
  | MetricsEvent
  | PluginTrustPromptEvent
  | PluginTrustAppliedEvent
  | SandboxStatusEvent
  | SandboxPrepareProgressEvent
  | SandboxReadyEvent
  | SandboxErrorEvent;
